name: demo
on: 
  workflow_dispatch

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run py test
        run: pytest --cov-report html:htmlcov --cov-report term --cov=project test
      - name: upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: htmlcov/
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: deploy code
        run: echo "deploy........."
