name: study-workflow-run
on: 
  workflow_dispatch

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run py test
        run: pytest --cov-report html:htmlcov --cov-report term --cov=project test
      - name: upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: htmlcov/
  
  deploy:
    runs-on: ubuntu-latest
    needs: test-code  #  表示test-code任务执行结束并且执行成功，deploy任务才会去执行
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: deploy code
        run: echo "deploy........."
